"use client";

import { useState, useMemo } from "react";
import { Send, CheckCircle } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { mockResults, mockStudents, mockCycles } from "@/lib/mock-data";
import { useToast } from "@/hooks/use-toast";
import { useAuth } from "@/lib/auth-context";
import { api } from "@/lib/api-client";
import { shouldUseRealAPI } from "@/lib/api-config";

const COMPETENCIES = [
  "Structural",
  "Civil",
  "Electrical",
  "Mechanical",
  "Software",
];
const CLASSES = ["Junior", "Wheeler", "Senior", "Lead"];

export default function VerifierReportPage() {
  const { toast } = useToast();
  const { user } = useAuth();
  const activeCycle = mockCycles.find((c) => c.status === "active");

  const [notes, setNotes] = useState("");
  const [sent, setSent] = useState(false);
  const [loading, setLoading] = useState(false);

  const allResults = useMemo(
    () => mockResults.filter((r) => r.status !== "draft"),
    [],
  );

  const byCompetency = useMemo(
    () =>
      COMPETENCIES.map((comp) => {
        const compResults = allResults.filter((r) => r.competency === comp);
        return {
          comp,
          total: compResults.length,
          approved: compResults.filter((r) => r.status === "approved").length,
          submitted: compResults.filter((r) => r.status === "submitted").length,
        };
      }).filter((c) => c.total > 0),
    [allResults],
  );

  const byClass = useMemo(
    () =>
      CLASSES.map((cls) => {
        const classStudents = mockStudents.filter((s) => s.gradeLevel === cls);
        const classResults = allResults.filter((r) =>
          classStudents.some((s) => s.id === r.studentId),
        );
        return {
          cls,
          students: classStudents.length,
          assessed: classResults.length,
          approved: classResults.filter((r) => r.status === "approved").length,
        };
      }).filter((c) => c.students > 0),
    [allResults],
  );

  const handleSend = async () => {
    if (!notes.trim()) {
      toast({
        title: "Required",
        description: "Please add report notes before sending.",
        variant: "destructive",
      });
      return;
    }

    if (!shouldUseRealAPI()) {
      setSent(true);
      toast({
        title: "Report Sent",
        description: "Your monitoring report has been sent to the Controller.",
      });
      return;
    }

    setLoading(true);
    try {
      // Generate summary content
      let content = `Monitoring Report for ${activeCycle?.name || "Current Cycle"}\n\n`;
      content += `Generated by: ${user?.fullName || "Verifier"}\n\n`;
      content += `PROGRESS BY COMPETENCY:\n`;
      byCompetency.forEach((c) => {
        content += `- ${c.comp}: ${c.approved}/${c.total} approved (${c.submitted} pending)\n`;
      });
      content += `\nPROGRESS BY CLASS:\n`;
      byClass.forEach((c) => {
        content += `- ${c.cls}: ${c.assessed}/${c.students} assessed, ${c.approved} approved\n`;
      });
      content += `\nNOTES:\n${notes}\n`;

      await api.reports.createControllerReport({
        cycleId: Number(activeCycle?.id) || 1,
        reportType: "Verifier Monitoring",
        title: `Monitoring Report - ${activeCycle?.name || "Cycle"}`,
        content: content,
        generatedBy: user?.accountId ? Number(user.accountId) : undefined,
      });

      // Log the activity
      await api.reports.createActivityLog({
        userId: user?.accountId ? Number(user.accountId) : undefined,
        actionType: "Report Sent",
        entityType: "ControllerReport",
        entityId: activeCycle?.id ? Number(activeCycle.id) : undefined,
        newValue: `Verifier sent monitoring report for ${activeCycle?.name}`,
      });

      setSent(true);
      toast({
        title: "Report Sent",
        description: "Your monitoring report has been sent to the Controller.",
      });
    } catch (error) {
      console.error("Failed to send report:", error);
      toast({
        title: "Error",
        description: "Failed to send report. Please try again.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 p-6 space-y-6">
      <div className="bg-primary text-primary-foreground p-8 rounded-[3px] border border-border/50 shadow-sm">
        <h1 className="text-3xl font-bold tracking-tight mb-2 uppercase">
          Send Report to Controller
        </h1>
        <p className="text-primary-foreground/80 text-sm font-medium tracking-wide">
          {activeCycle ? activeCycle.name.toUpperCase() : "NO ACTIVE CYCLE"} ·
          END-OF-ROUND MONITORING SUMMARY
        </p>
      </div>

      {/* By Competency */}
      <Card className="p-6 rounded-[3px] border-2 border-border shadow-sm">
        <h2 className="text-sm font-bold text-foreground mb-4 uppercase tracking-widest">
          Progress by Competency
        </h2>
        <div className="space-y-3">
          {byCompetency.length === 0 ? (
            <p className="text-sm text-gray-400">No submitted results yet.</p>
          ) : (
            byCompetency.map((c) => (
              <div key={c.comp} className="flex items-center gap-4">
                <span className="text-sm text-gray-700 w-28 shrink-0 font-medium">
                  {c.comp}
                </span>
                <div className="flex-1 bg-gray-100 rounded-full h-2.5">
                  <div
                    className="bg-green-500 h-2.5 rounded-full"
                    style={{
                      width:
                        c.total > 0 ? `${(c.approved / c.total) * 100}%` : "0%",
                    }}
                  />
                </div>
                <div className="flex gap-3 text-xs text-gray-500 w-48 shrink-0">
                  <span className="text-green-600 font-medium">
                    {c.approved} approved
                  </span>
                  <span className="text-amber-500">{c.submitted} pending</span>
                </div>
              </div>
            ))
          )}
        </div>
      </Card>

      {/* By Class */}
      <Card className="p-6 rounded-[3px] border-2 border-border shadow-sm">
        <h2 className="text-sm font-bold text-foreground mb-4 uppercase tracking-widest">
          Progress by Class
        </h2>
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          {byClass.map((c) => (
            <div
              key={c.cls}
              className="bg-secondary/50 rounded-[3px] border border-border p-5 text-center"
            >
              <p className="font-bold text-foreground uppercase tracking-wider text-sm">
                {c.cls}
              </p>
              <p className="text-3xl font-bold text-primary mt-2 tracking-tight">
                {c.assessed}
              </p>
              <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-widest mt-1">
                of {c.students} assessed
              </p>
              <p className="text-xs text-success font-bold mt-2 uppercase tracking-wider">
                {c.approved} approved
              </p>
            </div>
          ))}
        </div>
      </Card>

      {/* Report Notes */}
      <Card className="p-6 rounded-[3px] border-2 border-border shadow-sm">
        <h2 className="text-sm font-bold text-foreground mb-3 uppercase tracking-widest">
          Report Notes
        </h2>
        <p className="text-sm text-gray-500 mb-3">
          Summarize your observations for this cycle. This will be sent to the
          Controller.
        </p>
        <Textarea
          placeholder="e.g. Overall progress is on track. Structural competency has 2 pending results. Civil class shows strong performance..."
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          rows={6}
          disabled={sent}
          className="resize-none"
        />
      </Card>

      {sent ? (
        <div className="flex items-center gap-3 p-5 bg-success/10 border-2 border-success/20 rounded-[3px]">
          <CheckCircle className="w-5 h-5 text-success shrink-0" />
          <p className="text-sm font-bold text-success uppercase tracking-wider">
            Report sent to Controller successfully.
          </p>
        </div>
      ) : (
        <Button
          onClick={handleSend}
          disabled={loading}
          className="bg-primary hover:bg-primary/90 gap-2 font-bold"
          size="lg"
        >
          <Send className="w-5 h-5" />
          {loading ? "Sending..." : "Send Report to Controller"}
        </Button>
      )}
    </div>
  );
}
